# Generated by Django 4.1.5 on 2023-08-14 17:05

import MainModels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=MainModels.models.path_ava)),
            ],
        ),
        migrations.CreateModel(
            name='GameDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainModels.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=10)),
                ('map_veto', models.TextField()),
                ('data', models.DateField()),
                ('info', models.JSONField()),
                ('videofile', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=5)),
                ('ava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainModels.gallery')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_becoming_an_esportsman', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField(blank=True)),
                ('type_user', models.CharField(choices=[('CA', 'Captain'), ('PL', 'Player'), ('CO', 'Coach'), ('MA', 'Manager')], default='PL', max_length=2)),
                ('ava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainModels.gallery')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainModels.countrys')),
                ('main_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainModels.gamediscipline')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользовательли',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_start', models.DateField()),
                ('data_end', models.DateField()),
                ('ava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainModels.gallery')),
                ('schedule', models.ManyToManyField(to='MainModels.match')),
                ('teams', models.ManyToManyField(to='MainModels.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(blank=True, to='MainModels.tournament'),
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(to='MainModels.user'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='MainModels.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='MainModels.team'),
        ),
    ]
